version: "3"

services:
  query-node:
    build:
      context: .
      target: query-node
    ports:
      - 4000:4000
    environment:
      DB_HOST: db
    restart: unless-stopped

  processor:
     build:
       context: .
       target: processor
     environment:
       DB_HOST: db
     restart: unless-stopped

  migrate:
    build:
      context: .
      target: migrate
    environment:
      DB_HOST: db
    depends_on:
      - db

  db:
    image: postgres:12
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "${DB_PORT}:5432"
