version: '3'

networks:
  squid_web_network:
    external: true
    driver: bridge
  db_network:
    driver: bridge

services:
  query-node:
    build:
      context: .
      target: queryNode
    ports:
      - 4001
    environment:
      DB_HOST: db
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - squid_web_network
      - db_network

  khala-processor:
    build:
      context: .
      target: khalaProcessor
    environment:
      DB_HOST: db
    ports:
      - 3000
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - db_network

  kusama-processor:
    build:
      context: .
      target: kusamaProcessor
    environment:
      DB_HOST: db
    ports:
      - 3000
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - db_network

  polkadot-processor:
    build:
      context: .
      target: polkadotProcessor
    environment:
      DB_HOST: db
    ports:
      - 3000
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - db_network

  migrate:
    build:
      context: .
      target: migrate
    environment:
      DB_HOST: db
    depends_on:
      - db
    networks:
      - db_network

  db:
    image: postgres:12
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432
    networks:
      - db_network
